-- MySQL Script generated by MySQL Workbench
-- Mon Aug 21 07:45:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema InstituloLotus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema InstituloLotus
-- -----------------------------------------------------
drop database InstituloLotus;
CREATE SCHEMA IF NOT EXISTS `InstituloLotus` DEFAULT CHARACTER SET utf8 ;
USE `InstituloLotus` ;

-- -----------------------------------------------------
-- Table `InstituloLotus`.`Denúncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstituloLotus`.`Denúncia` (
  `den_protocolo` VARCHAR(8) NOT NULL PRIMARY KEY,
  `den_denunciante` VARCHAR(45) NOT NULL,
  `den_violencia` VARCHAR(45) NOT NULL,
  `den_frequencia` VARCHAR(45) NOT NULL,
  `den_data_ocorrencia` VARCHAR(10) NOT NULL,
  `den_hora_ocorrencia` VARCHAR(5) NOT NULL,
  `den_data_denuncia` VARCHAR(10) NOT NULL,
  `den_imagem` BLOB NULL,
  `den_local` VARCHAR(100) NOT NULL,
  `den_cep` NVARCHAR(8) NOT NULL,
  `den_ponto_ref` VARCHAR(55) NOT NULL,
  `den_carac_local` VARCHAR(100) NOT NULL
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstituloLotus`.`Polícia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstituloLotus`.`Polícia` (
  `pol_cpf` NVARCHAR(11) NOT NULL PRIMARY KEY,
  `pol_nome` VARCHAR(15) NULL,
  `pol_sobrenome` VARCHAR(30) NULL,
  `pol_email` VARCHAR(100) NULL,
  `pol_senha` VARCHAR(60) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstituloLotus`.`Acompanhamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstituloLotus`.`Acompanhamento` (
  `Denúncia_den_protocolo` VARCHAR(8) NOT NULL REFERENCES `InstituloLotus`.`Denúncia` (`den_protocolo`) 
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  `Polícia_pol_distintivo` NVARCHAR(11) NOT NULL REFERENCES `InstituloLotus`.`Polícia` (`pol_distintivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  `aco_id` INT PRIMARY KEY AUTO_INCREMENT,
  `pol_nome` VARCHAR(45) NULL,
  `aco_status` VARCHAR(200) NULL,
  `aco_comentario` VARCHAR(500) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstituloLotus`.`Agressor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstituloLotus`.`Agressor` (
  `agr_id` VARCHAR(5) NOT NULL PRIMARY KEY,
  `agr_nome` VARCHAR(45) NULL,
  `agr_idade` VARCHAR(45) NULL,
  `agr_sexo` VARCHAR(1) NULL,
  `agr_estatura` VARCHAR(45) NULL,
  `agr_tipo_fisico` VARCHAR(45) NULL,
  `agr_cor_pele` VARCHAR(45) NULL,
  `agr_cor_cabelo` VARCHAR(45) NULL,
  `agr_cor_olhos` VARCHAR(45) NULL,
  `agr_tipo_cabelo` VARCHAR(45) NULL,
  `agr_carac_espec` VARCHAR(45) NULL,
  `agr_possui_porte` VARCHAR(45) NULL,
  `agr_possibili_fuga` VARCHAR(45) NULL,
  `agr_endereco` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InstituloLotus`.`Denúncia_has_Agressor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `InstituloLotus`.`Denúncia_has_Agressor` (
  `Denúncia_den_protocolo` VARCHAR(8) NOT NULL REFERENCES `InstituloLotus`.`Denúncia` (`den_protocolo`) 
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  `Agressor_agr_id` VARCHAR(5) NOT NULL REFERENCES `InstituloLotus`.`Agressor` (`agr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

